name: Building JS
author: Mafiia__
description: 'An easy GA to build your JS projet without dependencies'
branding:
  icon: 'check'
  color: 'blue'
inputs:
  cmd:
    description: 'Add some config for vuejs project'
    required: true
  path:
    description: 'Add path to your vuejs project'
    required: true
runs:
  using: 'node10'
  args:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install dependences
      run: cd ${{inputs.path}} && ${{inputs.cmd}} install
    - name: build
      run: cd ${{inputs.path}} && ${{inputs.cmd}} run build
    - name: remove node_modules
      run: cd ${{inputs.path}} && rm -rf node_modules
    - name: create artifact
      uses: actions/upload-artifact@v1
      with:
        name: vue_projet
        path: ./${{inputs.path}}
